[tox]
envlist =
    py310-django{42,52}-tests
    py311-django{42,52}-tests
    py312-django{42,52,60}-tests
    lint

[testenv]
usedevelop = True
extras =
    test
setenv =
    PYTHONDONTWRITEBYTECODE=1
    PYTHONPATH={toxinidir}
deps =
    django42: Django>=4.2,<4.3
    django52: Django>=5.2,<5.3
    django60: Django>=6.0,<6.1
commands =
    pytest {posargs:tests} --cov-append --cov-report=xml --cov=frontend_settings
allowlist_externals=make

[testenv:lint]
extras = lint
commands =
    flake8 ./frontend_settings ./tests --ignore=E501
    isort --check-only --diff ./frontend_settings ./tests
    black --check --diff ./frontend_settings ./tests
